name: deploy to production
on:
  push:
    branches: [ cicd ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/dwh-his-backend      
          cd /apps/github-workflows/dwh-his-backend
          git pull origin master
          git status
          cp /apps/dockerApps/dwh-his-backend/his.dockerfile /apps/github-workflows/dwh-his-backend
          cp /apps/dockerApps/dwh-his-backend/nginx.dockerfile /apps/github-workflows/dwh-his-backend
          cp /apps/dockerApps/dwh-his-backend/docker-compose.yml /apps/github-workflows/dwh-his-backend
          cp /apps/dockerApps/dwh-his-backend/.env /apps/github-workflows/dwh-his-backend/mfl_interface/
          cp -r /apps/dockerApps/dwh-his-backend/docker/ /apps/github-workflows/dwh-his-backend
          docker-compose down
          docker-compose rm -f
          docker-compose up --build -d 
